Fix installation failures for versions 0.10.48, 0.12.18 and 5.12.0.
npm install for these versions is failing due to a bug that causes
installation of native modules to fail with the error:
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34):
error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers
[C:\projects\tedious\node_modules\sspi-client\build\sspi-client.vcxproj]

This seems to be a known issue with certain npm/node-gyp versions:
https://github.com/nodejs/node-gyp/issues/972
https://github.com/nodejs/node/issues/7286

Fixing this by installing the latest version of npm before running the
tests.