Work-around socket.connect bug in Node 7.7.2
Node 7.7.2 introduced a bug in socket.connect, where you get an error:
typeerror: "listener" argument must be a function

Switched to net.connect which does not have this bug.